"""i18n module for BBFlow bot — English Only."""
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
import db

TEXTS = {
    "start_admin": "✨ *BBFlow — ADMIN MODE* ✨\n━━━━━━━━━━━━━━━━━━━━━\n_Unlimited generation for admin._ 👑\n\n🖼️  /image — Image Mode\n🎬  /video — Video Mode\n📊  /stats — Bot statistics\n💳  /pending — Pending payments\n💰  /balance — Engine token balance\n\n💡 _Type / to see all commands_",
    "start_captcha": "👋 *Welcome to BBFlow!*\n━━━━━━━━━━━━━━━━━━━━━\n\n🤖 _Please verify you're human first_\n\n*What is:* `{q}` *?*\n\n_Tap the correct number:_ ",
    "start_welcome_main": "✨ *BBFlow* ✨\n━━━━━━━━━━━━━━━━━━━━━\n_BBFlow ready_ 🎨\n\n👤 Status: *{plan_label}*{free_status}\n\n🖼️  /image — Generate image\n🎬  /video — Generate video _(premium)_\n💎  /upgrade — Buy premium plan\n📊  /status — Check your plan\n📖  /help — How to use\n\n💡 _Type / to see all commands_",
    "plan_free": "🆓 FREE TRIAL",
    "plan_premium_until": "💎 PREMIUM _(until {date})_",
    "free_trial_exhausted": "\n⚠️ Free trial used up. Upgrade premium → /upgrade",
    "free_trial_remaining_line": "\n🎁 You have *{remaining}x* free image trial(s) left",
    "help_text": "📖 *BBFlow — Help*\n━━━━━━━━━━━━━━━━━━━━━\n\n🎁 *FREE TRIAL*\n  • 2x image generations (lifetime)\n  • After use: upgrade to premium required\n\n💎 *PREMIUM PLANS*\n  • Weekly: $50 / 7 days\n  • Monthly: $150 / 30 days\n  • Unlimited image + video generation\n  • Access to all models (Kling, Seedance)\n\n━━━━━━━━━━━━━━━━━━━━━\n🚀 *How to use:*\n1️⃣  Verify captcha at /start\n2️⃣  Send text → becomes prompt\n3️⃣  Tap 🖼️ Image / 🎬 Video\n4️⃣  Set preset, ratio, style\n5️⃣  Tap GENERATE — wait ~30s-3min\n\n━━━━━━━━━━━━━━━━━━━━━\n💳 *Buy Premium:*\n  /upgrade → pick plan + pay via QRIS\n  /pay <code> → upload screenshot\n  Admin approves manually within 1-12h",
    "verify_first": "🤖 Please verify via /start first",
    "verify_first_short": "⚠️ Please /start first.",
    "admin_only": "🔒 Admin only",
    "admin_only_long": "🔒 Admin-only command. Check your plan: /status",
    "menu_panel": "⚙️ *Control Panel*\n━━━━━━━━━━━━━━━━━━━━━",
    "session_reset": "🔄 *Session reset.*\n_Please reconfigure your options._",
    "image_free_intro": "🖼️ *Image Mode — Free Trial*\n━━━━━━━━━━━━━━━━━━━━━\n\n🎁 You get *2x free trials*\n🤖 Engine: *Auto* _(model picked automatically)_\n\n📝 *How to use:*\n1. Send text describing your image\n2. Tap the 🚀 GENERATE button\n3. Wait ~1-2 minutes\n\n💎 Want full control + unlimited?\n/upgrade for premium plan",
    "image_premium_intro": "🖼️ *Image Mode active*\n_Send your text prompt and tap GENERATE._",
    "video_premium_only": "🔒 *Video Mode = Premium Only*\n\nFree trial is for images only. Please upgrade:\n/upgrade",
    "video_intro": "🎬 *Video Mode active*\n_Send prompt + set model + GENERATE._",
    "status_admin": "👑 ADMIN (unlimited)",
    "status_free_used": "✅ used",
    "status_free_unused": "⏳ not used",
    "status_free_label": "🆓 FREE — trial {used}",
    "status_premium_label": "💎 *{plan}* _(until {exp})_",
    "status_block": "📊 *Your Account*\n━━━━━━━━━━━━━━━━━━━━━\n\n👤 ID: `{uid}`\n📋 Plan: {plan_str}\n🎨 Total gens: *{gen_count}*\n\n",
    "status_upgrade_hint": "💎 Upgrade: /upgrade\n",
    "upgrade_intro": "💎 *Choose Premium Plan*\n━━━━━━━━━━━━━━━━━━━━━\n\n📅 *Weekly* — $50 / 7 days\n  ✓ Unlimited image gen\n  ✓ Unlimited video gen\n  ✓ Access to all models\n\n⭐ *Monthly* — $150 / 30 days\n  ✓ Save *$50* vs weekly x 4\n  ✓ Same benefits\n\n💳 _Pay via QRIS, admin approves manually_",
    "upgrade_btn_weekly": "📅 Weekly — $50",
    "upgrade_btn_monthly": "⭐ Monthly — $150",
    "upgrade_btn_cancel": "❌ Cancel",
    "ref_block": "🎁 *BBFlow Referral Program*\n━━━━━━━━━━━━━━━━━━━━━\n\n📊 *Your Stats:*\n  • Total invites: *{total}*\n  • Successful:    *{granted}* ✅\n  • Pending:       *{pending}* ⏳\n  • Bonus trials:  *+{bonus}x* 🎁\n\n🎁 *Rewards:*\n  • You invite a friend: *+{br}x trial* per friend\n  • Friend joins:        gets *+{bi}x trial* bonus\n\n📤 *Your Invite Link:*\n`{link}`\n\n_Tap link to copy, then share with friends._\n\n💡 *Tips:*\n• Bonus activates after friend passes /start captcha\n• No invite limit\n• Bonuses keep stacking",
    "lang_picker": "🌐 *Language settings*\n━━━━━━━━━━━━━━━━━━━━━\n\nCurrently: 🇺🇸 *English Only*",
    "lang_set_id": "✅ Language changed to 🇺🇸 *English*",
    "lang_set_en": "✅ Language changed to 🇺🇸 *English*",
    "btn_image": "🖼️ Image",
    "btn_video": "🎬 Video",
    "btn_generate_image": "🚀 GENERATE IMAGE",
    "btn_generate_video": "🚀 GENERATE VIDEO",
    "btn_random_gen": "🎲 Random Prompt + Auto Generate Image",
    "btn_upgrade_premium": "💎 Upgrade Premium",
    "btn_reset": "🔄 Reset",
    "btn_balance": "💰 Token Balance",
    "btn_back": "⬅️ Back",
    "btn_lang": "🌐 Settings",
    "btn_free_trial_label": "🎁 Free Trial — Auto Mode",
    "btn_prompt_empty": "(empty — send text)",
    "captcha_expired": "⚠️ Captcha expired. Please /start again.",
    "captcha_wrong": "❌ Wrong answer. Try again:\n\n*What is:* `{q}` *?*",
    "captcha_referral_bonus": "\n\n🎁 *Referral Bonus!*\nYou got *+{n}x bonus free trials* because you were invited by a friend.",
    "captcha_verified": "✅ *Verified!*\n━━━━━━━━━━━━━━━━━━━━━\n\nWelcome to BBFlow! 🎉\nYou have 🎁 *{trials}x free image trial(s)*.{ref_msg}\n\nUse /image or /upgrade to start\n💡 Invite friends = bonus trials: /ref\n\n",
    "referrer_notif": "🎉 *Referral successful!*\n━━━━━━━━━━━━━━━━━━━━━\n\nYour friend just joined BBFlow 🎁\nYou got *+{n}x free trials*.\n\n📊 Successful invites: *{count}*\n💎 Check bonus: /ref",
    "upgrade_cancel": "❌ Upgrade cancelled.",
    "plan_label_weekly": "Weekly (7 days)",
    "plan_label_monthly": "Monthly (30 days)",
    "payment_created": "✅ *Payment Created*\n━━━━━━━━━━━━━━━━━━━━━\n\n🔑 Unique code: `{code}`\n📋 Plan: *{plan_label}*\n💰 Amount: *${amount:,}*\n\n📲 _Scan QRIS in the next message..._",
    "qris_caption": "💳 *Payment ${amount:,} via QRIS*\n━━━━━━━━━━━━━━━━━━━━━\n\n🔑 Your code: `{code}`\n\n📋 *Steps:*\n1️⃣  Scan QR and pay *${amount:,}*\n2️⃣  Screenshot the transfer receipt\n3️⃣  Send: `/pay {code}` then upload the photo\n\n⏳ Admin approves within 1-12 hours.\n_Auto-notification once activated._",
    "qris_unset": "⚠️ QRIS not configured on server.\nPlease contact admin manually.\n\nYour code: `{code}`",
    "premium_activated": "🎉 *PREMIUM ACTIVE!* 🎉\n━━━━━━━━━━━━━━━━━━━━━\n\n🔑 Code: `{code}`\n💎 Plan: *{plan}*\n📅 Expires: *{exp}*\n\nStart using /image or /video. 🚀",
    "screenshot_uploaded": "✅ uploaded",
    "screenshot_missing": "❌ pending",
    "pay_pending_block": "💳 *Your Pending Payment*\n━━━━━━━━━━━━━━━━━━━━━\n\n🔑 Code: `{code}`\n📋 Plan: *{plan}*\n💰 Amount: *${amount:,}*\n📸 Screenshot: {sshot}\n🕐 Requested: _{req}_\n\nHow to: `/pay {code}` then send transfer receipt photo.",
    "pay_no_pending": "💳 *No pending payment*\n\nCreate new payment: /upgrade",
    "pay_code_not_found": "❌ Code `{code}` not found",
    "pay_code_not_yours": "⛔ This code is not yours",
    "pay_code_already": "❌ This code is already `{status}`",
    "pay_send_screenshot": "📸 *Send transfer screenshot for:*\n\n🔑 `{code}`\n💰 ${amount:,}\n\n_Send photo now. Auto-attached._",
    "menu_panel_short": "⚙️ Generator Panel:",
    "mode_video_active": "🎬 *Video Mode*",
    "mode_image_active": "🖼️ *Image Mode*",
    "open_vmodel_title": "🎬 *Choose Video Model*\n\n_Kling V3 = latest, 1080p, audio support._\n_Veo 3 = Google, premium quality._",
    "open_var_title": "📐 *Choose Video Aspect Ratio*",
    "open_vdur_title": "⏱️ *Choose Duration (seconds)*",
    "open_vres_title": "🎯 *Choose Resolution*",
    "open_vqty_title": "🔢 *Choose Video Quantity (1-2)*",
    "audio_toggled": "🔊 Audio: *{state}*",
    "open_model_title": "🤖 *Choose Model*\n\n_Auto = BBFlow picks the best model for your prompt._",
    "open_ar_title": "📐 *Choose Aspect Ratio*",
    "open_style_title": "🎨 *Choose Style Preset*",
    "open_qty_title": "🔢 *Choose Quantity (1-4)*",
    "set_video_model": "✅ Video Model: *{val}*",
    "set_video_ar": "✅ Video Aspect: *{val}*",
    "set_video_dur": "✅ Duration: *{val}s*",
    "set_video_res": "✅ Resolution: *{val}*",
    "set_video_qty": "✅ Video Qty: *{val}*",
    "set_model": "✅ Model: *{val}*",
    "set_ar": "✅ Aspect: *{val}*",
    "set_style": "✅ Style: *{val}*",
    "set_qty": "✅ Quantity: *{val}*",
    "info_prompt_send": "📝 Send any text as a new prompt.",
    "info_freetrial_block": "🎁 *Free Trial Mode*\n━━━━━━━━━━━━━━━━━━━━━\n\nFree trial uses *Auto* engine.\nModel and style are picked automatically for best results.\n\n💎 For full control, premium model access (Phoenix, FLUX, Lucid), custom aspect ratios, and unlimited generation:\n\n/upgrade",
    "session_reset_short": "🔄 Session reset.",
    "balance_loading_short": "💰 Checking balance...",
    "balance_loading": "💰 _Checking balance..._",
    "balance_block": "💰 *Engine Token Balance*\n━━━━━━━━━━━━━━━━━━━━━\n\n👤 _{username}_\n💎 Plan: *{plan}*\n\n🪙  Image tokens: *{tokens:,}*\n📺  Stream tokens: {stream:,}\n💬  GPT tokens: {gpt:,}\n\n🔄 Renews: _{renewal}_",
    "balance_short": "💰 Image tokens: *{tokens:,}*\n📺 Stream: {stream:,}\n💎 Plan: {plan}",
    "error_label": "❌ Error: `{err}`",
    "no_prompt": "⚠️ Please send a prompt first (send text).",
    "trial_exhausted_block": "🔒 *Trial used up*\n━━━━━━━━━━━━━━━━━━━━━\n\nYou've used your free trials.\nTo continue, upgrade to premium:\n\n💎 /upgrade",
    "rate_limit": "⏳ Please wait {wait} seconds (rate limit).",
    "random_loading": "🎲 _Picking random prompt..._",
    "random_failed": "❌ Failed to generate random prompt. Try again or send your own prompt.",
    "random_success": "🎲 *Random prompt:*\n_{prompt}_\n\n_Auto-generating..._",
    "enhancing": "✨ _Enhancing your prompt..._",
    "gen_progress_header": "🚀 *Generating...*\n\n📝 Prompt: _{prompt}..._\n",
    "gen_enhanced_line": "✨ _Prompt auto-enhanced_\n",
    "gen_queue_line": "⏳ Queue: position *#{pos}*\n⏰ ETA: ~{eta:.0f} min\n",
    "gen_free_engine_line": "🤖 Engine: *Auto (Free Trial)*\n📐 Auto resolution\n\n_Wait ~1-2 minutes per gen..._",
    "gen_premium_engine_line": "🤖 Model: {model}\n📐 {ar} ({w}x{h})\n🎨 Style: {style}\n🔢 Quantity: {qty}\n\n_Wait ~10-30 seconds per gen..._",
    "gen_starting_now": "🚀 _Starting generation now..._\n",
    "gen_failed": "❌ Failed: {err}",
    "gen_no_files": "⚠️ Generation succeeded but no files were returned — try again.",
    "gen_caption_multi": "✅ {n} images done\n📝 _{prompt}..._",
    "gen_caption_single": "✅ Generated\n📝 _{prompt}..._",
    "trial_used_hint": "🎁 *Free trial used*\n━━━━━━━━━━━━━━━━━━━━━\n\nTo generate again, upgrade to premium:\n💎 /upgrade",
    "video_premium_only_short": "🔒 *Video Mode = Premium Only*\n\nFree trial is for images only. Please upgrade:\n💎 /upgrade",
    "video_gen_progress": "🚀 *Generating Video...*\n\n📝 Prompt: _{prompt}..._\n🎬 Model: {model}\n📐 {ar} ({w}x{h})\n⏱️ Duration: {dur}s\n🎯 Resolution: {res}\n🔊 Audio: {audio}\n🔢 Quantity: {qty}\n\n_Video takes ~1-3 minutes, please wait..._",
    "video_no_files": "⚠️ Video gen succeeded but no files were returned — try again.",
    "video_caption_first": "✅ Video {i}/{n}\n🎬 {model}\n⏱️ {dur}s @ {res}\n📝 _{prompt}..._"
}

def t(uid: int, key: str, **kwargs) -> str:
    text = TEXTS.get(key, f"[missing:{key}]")
    if kwargs:
        try:
            text = text.format(**kwargs)
        except Exception:
            pass
    return text

def lang_keyboard() -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup([[InlineKeyboardButton("🇺🇸 English", callback_data="lang:en")]])

def detect_lang_from_telegram(tg_lang_code: str | None) -> str:
    return "en"
